from pathlib import Path
import os
import sqlite3
import secrets
import shutil

from fastapi import FastAPI, Request, Form, UploadFile, File, HTTPException, Depends
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# =====================================================
# PATHS / DATABASE
# =====================================================

BASE = Path(__file__).resolve().parent
DB = BASE / "vishnu.db"
UPLOAD_DIR = BASE / "static" / "uploads"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

DATABASE_URL = os.getenv("DATABASE_URL")
USE_POSTGRES = bool(DATABASE_URL)

if USE_POSTGRES:
    import psycopg
    from psycopg.rows import dict_row


def get_db():
    if USE_POSTGRES:
        return psycopg.connect(DATABASE_URL, row_factory=dict_row)

    connection = sqlite3.connect(DB)
    connection.row_factory = sqlite3.Row
    return connection


def db_execute(connection, query, params=()):
    """Use the same ? placeholders for SQLite and PostgreSQL."""
    if USE_POSTGRES:
        query = query.replace("?", "%s")
    return connection.execute(query, params)


def init_database():
    connection = get_db()

    if USE_POSTGRES:
        connection.execute("""
            CREATE TABLE IF NOT EXISTS people (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                type TEXT NOT NULL,
                name TEXT NOT NULL,
                details TEXT DEFAULT '',
                review TEXT DEFAULT '',
                photo TEXT DEFAULT ''
            )
        """)

        connection.execute("""
            CREATE TABLE IF NOT EXISTS testimonials (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                review TEXT NOT NULL
            )
        """)

        connection.execute("""
            CREATE TABLE IF NOT EXISTS faculty (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                subject TEXT NOT NULL,
                description TEXT DEFAULT '',
                photo TEXT DEFAULT ''
            )
        """)
    else:
        connection.executescript("""
            CREATE TABLE IF NOT EXISTS people (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                type TEXT NOT NULL,
                name TEXT NOT NULL,
                details TEXT DEFAULT '',
                review TEXT DEFAULT '',
                photo TEXT DEFAULT ''
            );

            CREATE TABLE IF NOT EXISTS testimonials (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                review TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS faculty (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                subject TEXT NOT NULL,
                description TEXT DEFAULT '',
                photo TEXT DEFAULT ''
            );
        """)

    connection.commit()
    connection.close()


init_database()

# =====================================================
# ADMIN LOGIN
# =====================================================

ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "admin@gmail.com")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "Admin@12345")

active_tokens = set()

# =====================================================
# FASTAPI
# =====================================================

app = FastAPI(title="Vishnu PCM Classes")

# Vercel website -> Render API
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://vishnupcmwebsite.vercel.app",
        "http://localhost:5500",
        "http://127.0.0.1:5500",
    ],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =====================================================
# STATIC FILES
# =====================================================

app.mount(
    "/static",
    StaticFiles(directory=BASE / "static"),
    name="static"
)

# =====================================================
# WEBSITE / ADMIN
# =====================================================

@app.get("/", response_class=HTMLResponse)
async def home():
    return FileResponse(BASE / "admin.html")


@app.get("/admin", response_class=HTMLResponse)
async def admin():
    return FileResponse(BASE / "admin.html")


@app.get("/assets/admin.css")
async def admin_css():
    return FileResponse(BASE / "admin.css", media_type="text/css")


@app.get("/assets/admin.js")
async def admin_js():
    return FileResponse(BASE / "admin.js", media_type="application/javascript")


@app.get("/assets/style.css")
async def style_css():
    return FileResponse(BASE / "style.css", media_type="text/css")


@app.get("/assets/script.js")
async def script_js():
    return FileResponse(BASE / "script.js", media_type="application/javascript")

# =====================================================
# LOGIN
# =====================================================

class LoginData(BaseModel):
    email: str
    password: str


@app.post("/api/login")
async def login(data: LoginData):
    if data.email != ADMIN_EMAIL or data.password != ADMIN_PASSWORD:
        raise HTTPException(
            status_code=401,
            detail="Incorrect email or password"
        )

    token = secrets.token_urlsafe(32)
    active_tokens.add(token)

    return {
        "success": True,
        "access_token": token
    }

# =====================================================
# AUTHENTICATION
# =====================================================

def check_auth(request: Request):
    authorization = request.headers.get("Authorization", "")

    if not authorization.startswith("Bearer "):
        raise HTTPException(
            status_code=401,
            detail="Login required"
        )

    token = authorization.split(" ", 1)[1]

    if token not in active_tokens:
        raise HTTPException(
            status_code=401,
            detail="Invalid session"
        )

    return True

# =====================================================
# HELPERS
# =====================================================

def rows_as_dict(rows):
    return [dict(row) for row in rows]


def get_returned_id(cursor):
    row = cursor.fetchone()
    if not row:
        raise HTTPException(status_code=500, detail="Could not create record")
    return row["id"] if isinstance(row, dict) else row[0]

# =====================================================
# PUBLIC DATA
# =====================================================

@app.get("/api/public")
async def public_data():
    connection = get_db()

    toppers = rows_as_dict(
        db_execute(
            connection,
            """
            SELECT *
            FROM people
            WHERE type='topper'
            ORDER BY id DESC
            """
        ).fetchall()
    )

    alumni = rows_as_dict(
        db_execute(
            connection,
            """
            SELECT *
            FROM people
            WHERE type='alumni'
            ORDER BY id DESC
            """
        ).fetchall()
    )

    testimonials = rows_as_dict(
        db_execute(
            connection,
            """
            SELECT *
            FROM testimonials
            ORDER BY id DESC
            """
        ).fetchall()
    )

    faculty = rows_as_dict(
        db_execute(
            connection,
            """
            SELECT *
            FROM faculty
            ORDER BY id DESC
            """
        ).fetchall()
    )

    connection.close()

    return {
        "toppers": toppers,
        "alumni": alumni,
        "testimonials": testimonials,
        "faculty": faculty
    }

# =====================================================
# ADMIN DATA
# =====================================================

@app.get("/api/admin/data")
async def admin_data(_: bool = Depends(check_auth)):
    return await public_data()

# =====================================================
# ADD TOPPER / ALUMNI
# =====================================================

@app.post("/api/admin/people")
async def add_person(
    type: str = Form(...),
    name: str = Form(...),
    details: str = Form(""),
    review: str = Form(""),
    photo: UploadFile | None = File(None),
    _: bool = Depends(check_auth)
):
    if type not in ["topper", "alumni"]:
        raise HTTPException(status_code=400, detail="Invalid type")

    photo_url = ""

    if photo and photo.filename:
        extension = Path(photo.filename).suffix.lower()
        allowed_extensions = [".jpg", ".jpeg", ".png", ".webp"]

        if extension not in allowed_extensions:
            raise HTTPException(
                status_code=400,
                detail="Only JPG, JPEG, PNG and WEBP images are allowed"
            )

        filename = secrets.token_hex(12) + extension
        file_path = UPLOAD_DIR / filename

        with file_path.open("wb") as buffer:
            shutil.copyfileobj(photo.file, buffer)

        photo_url = "/static/uploads/" + filename

    connection = get_db()

    cursor = db_execute(
        connection,
        """
        INSERT INTO people (type, name, details, review, photo)
        VALUES (?, ?, ?, ?, ?)
        RETURNING id
        """,
        (type, name, details, review, photo_url)
    )

    connection.commit()
    new_id = get_returned_id(cursor)
    connection.close()

    return {
        "success": True,
        "id": new_id,
        "photo": photo_url
    }

# =====================================================
# ADD REVIEW
# =====================================================

class ReviewData(BaseModel):
    name: str
    review: str


@app.post("/api/admin/testimonials")
async def add_testimonial(
    data: ReviewData,
    _: bool = Depends(check_auth)
):
    connection = get_db()

    cursor = db_execute(
        connection,
        """
        INSERT INTO testimonials (name, review)
        VALUES (?, ?)
        RETURNING id
        """,
        (data.name, data.review)
    )

    connection.commit()
    new_id = get_returned_id(cursor)
    connection.close()

    return {
        "success": True,
        "id": new_id
    }

# =====================================================
# ADD FACULTY
# =====================================================

@app.post("/api/admin/faculty")
async def add_faculty(
    name: str = Form(...),
    subject: str = Form(...),
    description: str = Form(""),
    photo: UploadFile | None = File(None),
    _: bool = Depends(check_auth)
):
    photo_url = ""

    if photo and photo.filename:
        extension = Path(photo.filename).suffix.lower()
        allowed_extensions = [".jpg", ".jpeg", ".png", ".webp"]

        if extension not in allowed_extensions:
            raise HTTPException(
                status_code=400,
                detail="Only JPG, JPEG, PNG and WEBP images are allowed"
            )

        filename = secrets.token_hex(12) + extension
        file_path = UPLOAD_DIR / filename

        with file_path.open("wb") as buffer:
            shutil.copyfileobj(photo.file, buffer)

        photo_url = "/static/uploads/" + filename

    connection = get_db()

    cursor = db_execute(
        connection,
        """
        INSERT INTO faculty (name, subject, description, photo)
        VALUES (?, ?, ?, ?)
        RETURNING id
        """,
        (name, subject, description, photo_url)
    )

    connection.commit()
    new_id = get_returned_id(cursor)
    connection.close()

    return {
        "success": True,
        "id": new_id,
        "photo": photo_url
    }

# =====================================================
# DELETE REVIEW
# =====================================================

@app.delete("/api/admin/review/{review_id}")
async def delete_review(
    review_id: int,
    _: bool = Depends(check_auth)
):
    connection = get_db()

    db_execute(
        connection,
        "DELETE FROM testimonials WHERE id=?",
        (review_id,)
    )

    connection.commit()
    connection.close()

    return {"success": True}

# =====================================================
# DELETE TOPPER
# =====================================================

@app.delete("/api/admin/topper/{person_id}")
async def delete_topper(
    person_id: int,
    _: bool = Depends(check_auth)
):
    connection = get_db()

    person = db_execute(
        connection,
        """
        SELECT photo
        FROM people
        WHERE id=? AND type='topper'
        """,
        (person_id,)
    ).fetchone()

    if not person:
        connection.close()
        raise HTTPException(status_code=404, detail="Topper not found")

    photo = person["photo"] if isinstance(person, dict) else person["photo"]

    if photo:
        image_path = BASE / photo.lstrip("/")
        if image_path.exists():
            image_path.unlink()

    db_execute(
        connection,
        "DELETE FROM people WHERE id=? AND type='topper'",
        (person_id,)
    )

    connection.commit()
    connection.close()

    return {"success": True}

# =====================================================
# DELETE ALUMNI
# =====================================================

@app.delete("/api/admin/alumni/{person_id}")
async def delete_alumni(
    person_id: int,
    _: bool = Depends(check_auth)
):
    connection = get_db()

    person = db_execute(
        connection,
        """
        SELECT photo
        FROM people
        WHERE id=? AND type='alumni'
        """,
        (person_id,)
    ).fetchone()

    if not person:
        connection.close()
        raise HTTPException(status_code=404, detail="Alumni not found")

    photo = person["photo"] if isinstance(person, dict) else person["photo"]

    if photo:
        image_path = BASE / photo.lstrip("/")
        if image_path.exists():
            image_path.unlink()

    db_execute(
        connection,
        "DELETE FROM people WHERE id=? AND type='alumni'",
        (person_id,)
    )

    connection.commit()
    connection.close()

    return {"success": True}

# =====================================================
# DELETE FACULTY
# =====================================================

@app.delete("/api/admin/faculty/{faculty_id}")
async def delete_faculty(
    faculty_id: int,
    _: bool = Depends(check_auth)
):
    connection = get_db()

    faculty = db_execute(
        connection,
        "SELECT photo FROM faculty WHERE id=?",
        (faculty_id,)
    ).fetchone()

    if not faculty:
        connection.close()
        raise HTTPException(status_code=404, detail="Faculty not found")

    photo = faculty["photo"] if isinstance(faculty, dict) else faculty["photo"]

    if photo:
        image_path = BASE / photo.lstrip("/")
        if image_path.exists():
            image_path.unlink()

    db_execute(
        connection,
        "DELETE FROM faculty WHERE id=?",
        (faculty_id,)
    )

    connection.commit()
    connection.close()

    return {"success": True}
