import cloudinary
import cloudinary.uploader

from pathlib import Path
import os
import sqlite3
import secrets
import shutil
import re

from fastapi import (
    FastAPI,
    Request,
    Form,
    UploadFile,
    File,
    HTTPException,
    Depends
)

from fastapi.responses import HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware


# =========================================================
# BASIC CONFIG
# =========================================================

BASE = Path(__file__).resolve().parent

DB = BASE / "vishnu.db"

UPLOAD_DIR = BASE / "static" / "uploads"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)


# =========================================================
# DATABASE
# =========================================================

DATABASE_URL = os.getenv("DATABASE_URL")
USE_POSTGRES = bool(DATABASE_URL)

if USE_POSTGRES:
    import psycopg
    from psycopg.rows import dict_row


def get_db():
    if USE_POSTGRES:
        return psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row
        )

    connection = sqlite3.connect(DB)
    connection.row_factory = sqlite3.Row

    return connection


def db_execute(connection, query, params=()):

    if USE_POSTGRES:
        query = query.replace("?", "%s")

    return connection.execute(query, params)


def rows_as_dict(rows):

    return [dict(row) for row in rows]


def get_returned_id(cursor):

    row = cursor.fetchone()

    if isinstance(row, dict):
        return row["id"]

    return row[0]


# =========================================================
# CLOUDINARY
# =========================================================

CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")


if (
    CLOUDINARY_CLOUD_NAME
    and CLOUDINARY_API_KEY
    and CLOUDINARY_API_SECRET
):

    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True
    )


def upload_image_to_cloudinary(photo, folder):

    if not (
        CLOUDINARY_CLOUD_NAME
        and CLOUDINARY_API_KEY
        and CLOUDINARY_API_SECRET
    ):
        raise HTTPException(
            status_code=500,
            detail="Cloudinary is not configured"
        )

    try:

        result = cloudinary.uploader.upload(
            photo.file,
            folder=folder,
            resource_type="image"
        )

        return result["secure_url"]

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=f"Cloudinary upload failed: {str(error)}"
        )


def upload_gallery_image_to_cloudinary(photo, folder):

    if not (
        CLOUDINARY_CLOUD_NAME
        and CLOUDINARY_API_KEY
        and CLOUDINARY_API_SECRET
    ):
        raise HTTPException(
            status_code=500,
            detail="Cloudinary is not configured"
        )

    try:

        result = cloudinary.uploader.upload(
            photo.file,
            folder=folder,
            resource_type="image"
        )

        return (
            result["secure_url"],
            result.get("public_id", "")
        )

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=f"Cloudinary upload failed: {str(error)}"
        )


def delete_cloudinary_image(public_id):

    if not public_id:
        return

    try:

        cloudinary.uploader.destroy(
            public_id,
            resource_type="image"
        )

    except Exception:

        pass


# =========================================================
# DATABASE INITIALIZATION
# =========================================================

def init_database():

    connection = get_db()

    if USE_POSTGRES:

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS people (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                type VARCHAR(50) NOT NULL,
                name VARCHAR(200) NOT NULL,
                details TEXT DEFAULT '',
                review TEXT DEFAULT '',
                photo TEXT DEFAULT ''
            )
            """
        )

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS testimonials (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                review TEXT DEFAULT ''
            )
            """
        )

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS faculty (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                subject VARCHAR(200) NOT NULL,
                description TEXT DEFAULT '',
                photo TEXT DEFAULT ''
            )
            """
        )

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS gallery_events (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(200) NOT NULL,
                description TEXT DEFAULT '',
                event_date VARCHAR(50) DEFAULT '',
                cover_photo TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS gallery_photos (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_id INTEGER NOT NULL
                    REFERENCES gallery_events(id)
                    ON DELETE CASCADE,
                photo_url TEXT NOT NULL,
                public_id TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

    else:

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS people (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                type TEXT NOT NULL,
                name TEXT NOT NULL,
                details TEXT DEFAULT '',
                review TEXT DEFAULT '',
                photo TEXT DEFAULT ''
            )
            """
        )

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS testimonials (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                review TEXT DEFAULT ''
            )
            """
        )

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS faculty (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                subject TEXT NOT NULL,
                description TEXT DEFAULT '',
                photo TEXT DEFAULT ''
            )
            """
        )

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS gallery_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                description TEXT DEFAULT '',
                event_date TEXT DEFAULT '',
                cover_photo TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        db_execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS gallery_photos (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                event_id INTEGER NOT NULL,
                photo_url TEXT NOT NULL,
                public_id TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

    connection.commit()
    connection.close()


init_database()


# =========================================================
# APP
# =========================================================

app = FastAPI(
    title="Vishnu PCM Classes Admin API"
)


# =========================================================
# CORS
# =========================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://vishnupcmwebsite.vercel.app",
        "http://localhost:5500",
        "http://127.0.0.1:5500"
    ],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"]
)


# =========================================================
# AUTH
# =========================================================

ADMIN_EMAIL = os.getenv(
    "ADMIN_EMAIL",
    "admin@gmail.com"
)

ADMIN_PASSWORD = os.getenv(
    "ADMIN_PASSWORD",
    "Admin@12345"
)

active_tokens = set()


# =========================================================
# FILE ROUTES
# =========================================================

@app.get("/", response_class=HTMLResponse)
async def root():

    return FileResponse(
        BASE / "admin.html"
    )


@app.get("/admin", response_class=HTMLResponse)
async def admin_page():

    return FileResponse(
        BASE / "admin.html"
    )


@app.get("/assets/admin.css")
async def admin_css():

    return FileResponse(
        BASE / "admin.css"
    )


@app.get("/assets/admin.js")
async def admin_js():

    return FileResponse(
        BASE / "admin.js"
    )


@app.get("/assets/style.css")
async def style_css():

    file_path = BASE / "style.css"

    if file_path.exists():
        return FileResponse(file_path)

    raise HTTPException(
        status_code=404,
        detail="style.css not found"
    )


@app.get("/assets/script.js")
async def script_js():

    file_path = BASE / "script.js"

    if file_path.exists():
        return FileResponse(file_path)

    raise HTTPException(
        status_code=404,
        detail="script.js not found"
    )


app.mount(
    "/static",
    StaticFiles(directory=UPLOAD_DIR.parent),
    name="static"
)


# =========================================================
# LOGIN
# =========================================================

@app.post("/api/login")
async def login(
    email: str = Form(...),
    password: str = Form(...)
):

    if (
        email != ADMIN_EMAIL
        or password != ADMIN_PASSWORD
    ):
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password"
        )

    token = secrets.token_urlsafe(32)

    active_tokens.add(token)

    return {
        "success": True,
        "token": token
    }


# =========================================================
# AUTH CHECK
# =========================================================

async def check_auth(request: Request):

    authorization = request.headers.get(
        "Authorization",
        ""
    )

    if not authorization.startswith("Bearer "):

        raise HTTPException(
            status_code=401,
            detail="Unauthorized"
        )

    token = authorization.replace(
        "Bearer ",
        "",
        1
    ).strip()

    if token not in active_tokens:

        raise HTTPException(
            status_code=401,
            detail="Invalid or expired token"
        )

    return True


# =========================================================
# PUBLIC DATA
# =========================================================

async def public_data():

    connection = get_db()

    toppers_cursor = db_execute(
        connection,
        """
        SELECT *
        FROM people
        WHERE type = ?
        ORDER BY id DESC
        """,
        ("topper",)
    )

    alumni_cursor = db_execute(
        connection,
        """
        SELECT *
        FROM people
        WHERE type = ?
        ORDER BY id DESC
        """,
        ("alumni",)
    )

    testimonials_cursor = db_execute(
        connection,
        """
        SELECT *
        FROM testimonials
        ORDER BY id DESC
        """
    )

    faculty_cursor = db_execute(
        connection,
        """
        SELECT *
        FROM faculty
        ORDER BY id DESC
        """
    )

    toppers = rows_as_dict(
        toppers_cursor.fetchall()
    )

    alumni = rows_as_dict(
        alumni_cursor.fetchall()
    )

    testimonials = rows_as_dict(
        testimonials_cursor.fetchall()
    )

    faculty = rows_as_dict(
        faculty_cursor.fetchall()
    )

    connection.close()

    return {
        "toppers": toppers,
        "alumni": alumni,
        "testimonials": testimonials,
        "faculty": faculty
    }


@app.get("/api/public")
async def get_public_data():

    return await public_data()


# =========================================================
# ADMIN DATA
# =========================================================

@app.get("/api/admin/data")
async def get_admin_data(
    _: bool = Depends(check_auth)
):

    return await public_data()


# =========================================================
# ADD TOPPER / ALUMNI
# =========================================================

@app.post("/api/admin/people")
async def add_person(

    type: str = Form(...),
    name: str = Form(...),
    details: str = Form(""),
    review: str = Form(""),
    photo: UploadFile | None = File(None),
    _: bool = Depends(check_auth)
):

    if type not in [
        "topper",
        "alumni"
    ]:

        raise HTTPException(
            status_code=400,
            detail="Invalid type"
        )

    photo_url = ""

    if photo and photo.filename:

        extension = Path(
            photo.filename
        ).suffix.lower()

        allowed_extensions = [
            ".jpg",
            ".jpeg",
            ".png",
            ".webp"
        ]

        if extension not in allowed_extensions:

            raise HTTPException(
                status_code=400,
                detail="Only JPG, JPEG, PNG and WEBP images are allowed"
            )

        photo_url = upload_image_to_cloudinary(
            photo,
            "vishnu-pcm/toppers-alumni"
        )

    connection = get_db()

    cursor = db_execute(
        connection,
        """
        INSERT INTO people
        (type, name, details, review, photo)
        VALUES (?, ?, ?, ?, ?)
        RETURNING id
        """,
        (
            type,
            name,
            details,
            review,
            photo_url
        )
    )

    connection.commit()

    new_id = get_returned_id(cursor)

    connection.close()

    return {
        "success": True,
        "id": new_id,
        "photo": photo_url
    }


# =========================================================
# ADD FACULTY
# =========================================================

@app.post("/api/admin/faculty")
async def add_faculty(

    name: str = Form(...),
    subject: str = Form(...),
    description: str = Form(""),
    photo: UploadFile | None = File(None),
    _: bool = Depends(check_auth)
):

    photo_url = ""

    if photo and photo.filename:

        extension = Path(
            photo.filename
        ).suffix.lower()

        allowed_extensions = [
            ".jpg",
            ".jpeg",
            ".png",
            ".webp"
        ]

        if extension not in allowed_extensions:

            raise HTTPException(
                status_code=400,
                detail="Only JPG, JPEG, PNG and WEBP images are allowed"
            )

        photo_url = upload_image_to_cloudinary(
            photo,
            "vishnu-pcm/faculty"
        )

    connection = get_db()

    cursor = db_execute(
        connection,
        """
        INSERT INTO faculty
        (name, subject, description, photo)
        VALUES (?, ?, ?, ?)
        RETURNING id
        """,
        (
            name,
            subject,
            description,
            photo_url
        )
    )

    connection.commit()

    new_id = get_returned_id(cursor)

    connection.close()

    return {
        "success": True,
        "id": new_id,
        "photo": photo_url
    }


# =========================================================
# ADD REVIEW
# =========================================================

@app.post("/api/admin/testimonials")
async def add_testimonial(

    name: str = Form(...),
    review: str = Form(""),
    _: bool = Depends(check_auth)
):

    connection = get_db()

    cursor = db_execute(
        connection,
        """
        INSERT INTO testimonials
        (name, review)
        VALUES (?, ?)
        RETURNING id
        """,
        (
            name,
            review
        )
    )

    connection.commit()

    new_id = get_returned_id(cursor)

    connection.close()

    return {
        "success": True,
        "id": new_id
    }


# =========================================================
# DELETE TOPPER
# =========================================================

@app.delete("/api/admin/topper/{person_id}")
async def delete_topper(
    person_id: int,
    _: bool = Depends(check_auth)
):

    connection = get_db()

    db_execute(
        connection,
        """
        DELETE FROM people
        WHERE id = ?
        AND type = ?
        """,
        (
            person_id,
            "topper"
        )
    )

    connection.commit()
    connection.close()

    return {
        "success": True
    }


# =========================================================
# DELETE ALUMNI
# =========================================================

@app.delete("/api/admin/alumni/{person_id}")
async def delete_alumni(
    person_id: int,
    _: bool = Depends(check_auth)
):

    connection = get_db()

    db_execute(
        connection,
        """
        DELETE FROM people
        WHERE id = ?
        AND type = ?
        """,
        (
            person_id,
            "alumni"
        )
    )

    connection.commit()
    connection.close()

    return {
        "success": True
    }


# =========================================================
# DELETE FACULTY
# =========================================================

@app.delete("/api/admin/faculty/{faculty_id}")
async def delete_faculty(
    faculty_id: int,
    _: bool = Depends(check_auth)
):

    connection = get_db()

    db_execute(
        connection,
        """
        DELETE FROM faculty
        WHERE id = ?
        """,
        (faculty_id,)
    )

    connection.commit()
    connection.close()

    return {
        "success": True
    }


# =========================================================
# DELETE REVIEW
# =========================================================

@app.delete("/api/admin/review/{review_id}")
async def delete_review(
    review_id: int,
    _: bool = Depends(check_auth)
):

    connection = get_db()

    db_execute(
        connection,
        """
        DELETE FROM testimonials
        WHERE id = ?
        """,
        (review_id,)
    )

    connection.commit()
    connection.close()

    return {
        "success": True
    }


# =========================================================
# GALLERY HELPERS
# =========================================================

def make_gallery_slug(title):

    slug = title.lower().strip()

    slug = re.sub(
        r"[^a-z0-9]+",
        "-",
        slug
    )

    slug = slug.strip("-")

    if not slug:
        slug = "event"

    return slug


def get_gallery_data():

    connection = get_db()

    event_cursor = db_execute(
        connection,
        """
        SELECT
            id,
            title,
            description,
            event_date,
            cover_photo,
            created_at
        FROM gallery_events
        ORDER BY id DESC
        """
    )

    events = rows_as_dict(
        event_cursor.fetchall()
    )

    result = []

    for event in events:

        photo_cursor = db_execute(
            connection,
            """
            SELECT
                id,
                event_id,
                photo_url,
                public_id,
                created_at
            FROM gallery_photos
            WHERE event_id = ?
            ORDER BY id DESC
            """,
            (event["id"],)
        )

        photos = rows_as_dict(
            photo_cursor.fetchall()
        )

        event["photos"] = photos
        event["photo_count"] = len(photos)

        result.append(event)

    connection.close()

    return result


# =========================================================
# PUBLIC GALLERY
# =========================================================

@app.get("/api/gallery")
async def get_public_gallery():

    return {
        "gallery": get_gallery_data()
    }


# =========================================================
# ADMIN GALLERY
# =========================================================

@app.get("/api/admin/gallery")
async def get_admin_gallery(
    _: bool = Depends(check_auth)
):

    return {
        "gallery": get_gallery_data()
    }


# =========================================================
# CREATE GALLERY EVENT
# =========================================================

@app.post("/api/admin/gallery/event")
async def create_gallery_event(

    title: str = Form(...),
    description: str = Form(""),
    event_date: str = Form(""),
    cover_photo: UploadFile | None = File(None),
    _: bool = Depends(check_auth)
):

    title = title.strip()

    if not title:

        raise HTTPException(
            status_code=400,
            detail="Event title is required"
        )

    cover_url = ""

    if cover_photo and cover_photo.filename:

        extension = Path(
            cover_photo.filename
        ).suffix.lower()

        allowed_extensions = [
            ".jpg",
            ".jpeg",
            ".png",
            ".webp"
        ]

        if extension not in allowed_extensions:

            raise HTTPException(
                status_code=400,
                detail="Only JPG, JPEG, PNG and WEBP images are allowed"
            )

        slug = make_gallery_slug(title)

        cover_url, _ = upload_gallery_image_to_cloudinary(
            cover_photo,
            f"vishnu-pcm/gallery/{slug}"
        )

    connection = get_db()

    cursor = db_execute(
        connection,
        """
        INSERT INTO gallery_events
        (
            title,
            description,
            event_date,
            cover_photo
        )
        VALUES (?, ?, ?, ?)
        RETURNING id
        """,
        (
            title,
            description,
            event_date,
            cover_url
        )
    )

    connection.commit()

    event_id = get_returned_id(cursor)

    connection.close()

    return {
        "success": True,
        "id": event_id,
        "cover_photo": cover_url
    }


# =========================================================
# UPLOAD MULTIPLE GALLERY PHOTOS
# =========================================================

@app.post("/api/admin/gallery/{event_id}/photos")
async def upload_gallery_photos(

    event_id: int,
    photos: list[UploadFile] = File(...),
    _: bool = Depends(check_auth)
):

    connection = get_db()

    event_cursor = db_execute(
        connection,
        """
        SELECT *
        FROM gallery_events
        WHERE id = ?
        """,
        (event_id,)
    )

    event = event_cursor.fetchone()

    if not event:

        connection.close()

        raise HTTPException(
            status_code=404,
            detail="Gallery event not found"
        )

    event_title = (
        event["title"]
        if isinstance(event, dict)
        else event[1]
    )

    slug = make_gallery_slug(
        event_title
    )

    uploaded = []

    allowed_extensions = [
        ".jpg",
        ".jpeg",
        ".png",
        ".webp"
    ]

    for photo in photos:

        if not photo or not photo.filename:
            continue

        extension = Path(
            photo.filename
        ).suffix.lower()

        if extension not in allowed_extensions:

            continue

        photo_url, public_id = (
            upload_gallery_image_to_cloudinary(
                photo,
                f"vishnu-pcm/gallery/{slug}"
            )
        )

        cursor = db_execute(
            connection,
            """
            INSERT INTO gallery_photos
            (
                event_id,
                photo_url,
                public_id
            )
            VALUES (?, ?, ?)
            RETURNING id
            """,
            (
                event_id,
                photo_url,
                public_id
            )
        )

        photo_id = get_returned_id(cursor)

        uploaded.append({
            "id": photo_id,
            "photo_url": photo_url
        })

    if uploaded:

        cover_cursor = db_execute(
            connection,
            """
            SELECT cover_photo
            FROM gallery_events
            WHERE id = ?
            """,
            (event_id,)
        )

        cover_row = cover_cursor.fetchone()

        current_cover = (
            cover_row["cover_photo"]
            if isinstance(cover_row, dict)
            else cover_row[0]
        )

        if not current_cover:

            db_execute(
                connection,
                """
                UPDATE gallery_events
                SET cover_photo = ?
                WHERE id = ?
                """,
                (
                    uploaded[0]["photo_url"],
                    event_id
                )
            )

    connection.commit()
    connection.close()

    return {
        "success": True,
        "uploaded": uploaded,
        "count": len(uploaded)
    }


# =========================================================
# SET GALLERY COVER
# =========================================================

@app.put(
    "/api/admin/gallery/{event_id}/cover/{photo_id}"
)
async def set_gallery_cover(

    event_id: int,
    photo_id: int,
    _: bool = Depends(check_auth)
):

    connection = get_db()

    photo_cursor = db_execute(
        connection,
        """
        SELECT photo_url
        FROM gallery_photos
        WHERE id = ?
        AND event_id = ?
        """,
        (
            photo_id,
            event_id
        )
    )

    photo = photo_cursor.fetchone()

    if not photo:

        connection.close()

        raise HTTPException(
            status_code=404,
            detail="Photo not found"
        )

    photo_url = (
        photo["photo_url"]
        if isinstance(photo, dict)
        else photo[0]
    )

    db_execute(
        connection,
        """
        UPDATE gallery_events
        SET cover_photo = ?
        WHERE id = ?
        """,
        (
            photo_url,
            event_id
        )
    )

    connection.commit()
    connection.close()

    return {
        "success": True,
        "cover_photo": photo_url
    }


# =========================================================
# DELETE GALLERY PHOTO
# =========================================================

@app.delete(
    "/api/admin/gallery/photo/{photo_id}"
)
async def delete_gallery_photo(

    photo_id: int,
    _: bool = Depends(check_auth)
):

    connection = get_db()

    cursor = db_execute(
        connection,
        """
        SELECT
            id,
            event_id,
            photo_url,
            public_id
        FROM gallery_photos
        WHERE id = ?
        """,
        (photo_id,)
    )

    photo = cursor.fetchone()

    if not photo:

        connection.close()

        raise HTTPException(
            status_code=404,
            detail="Photo not found"
        )

    if isinstance(photo, dict):

        event_id = photo["event_id"]
        photo_url = photo["photo_url"]
        public_id = photo["public_id"]

    else:

        event_id = photo[1]
        photo_url = photo[2]
        public_id = photo[3]

    delete_cloudinary_image(
        public_id
    )

    db_execute(
        connection,
        """
        DELETE FROM gallery_photos
        WHERE id = ?
        """,
        (photo_id,)
    )

    cover_cursor = db_execute(
        connection,
        """
        SELECT cover_photo
        FROM gallery_events
        WHERE id = ?
        """,
        (event_id,)
    )

    cover_row = cover_cursor.fetchone()

    current_cover = (
        cover_row["cover_photo"]
        if isinstance(cover_row, dict)
        else cover_row[0]
    )

    if current_cover == photo_url:

        new_cover_cursor = db_execute(
            connection,
            """
            SELECT photo_url
            FROM gallery_photos
            WHERE event_id = ?
            ORDER BY id DESC
            LIMIT 1
            """,
            (event_id,)
        )

        new_cover = new_cover_cursor.fetchone()

        if new_cover:

            new_cover_url = (
                new_cover["photo_url"]
                if isinstance(new_cover, dict)
                else new_cover[0]
            )

        else:

            new_cover_url = ""

        db_execute(
            connection,
            """
            UPDATE gallery_events
            SET cover_photo = ?
            WHERE id = ?
            """,
            (
                new_cover_url,
                event_id
            )
        )

    connection.commit()
    connection.close()

    return {
        "success": True
    }


# =========================================================
# DELETE COMPLETE GALLERY EVENT
# =========================================================

@app.delete(
    "/api/admin/gallery/event/{event_id}"
)
async def delete_gallery_event(

    event_id: int,
    _: bool = Depends(check_auth)
):

    connection = get_db()

    event_cursor = db_execute(
        connection,
        """
        SELECT id
        FROM gallery_events
        WHERE id = ?
        """,
        (event_id,)
    )

    event = event_cursor.fetchone()

    if not event:

        connection.close()

        raise HTTPException(
            status_code=404,
            detail="Gallery event not found"
        )

    photo_cursor = db_execute(
        connection,
        """
        SELECT public_id
        FROM gallery_photos
        WHERE event_id = ?
        """,
        (event_id,)
    )

    photos = photo_cursor.fetchall()

    for photo in photos:

        public_id = (
            photo["public_id"]
            if isinstance(photo, dict)
            else photo[0]
        )

        delete_cloudinary_image(
            public_id
        )

    # Explicit delete for SQLite compatibility
    db_execute(
        connection,
        """
        DELETE FROM gallery_photos
        WHERE event_id = ?
        """,
        (event_id,)
    )

    db_execute(
        connection,
        """
        DELETE FROM gallery_events
        WHERE id = ?
        """,
        (event_id,)
    )

    connection.commit()
    connection.close()

    return {
        "success": True
    }